'use strict';

//  В этом файле хранятся константы

(function () {
  var AVATAR_WIDTH = 40;
  var AVATAR_HEIGHT = 40;
  var MAINPIN_WIDTH = 62;
  var MAINPIN_HEIGHT = 62;
  var MAINPIN_END_HEIGHT = 22;
  var ENTER_KEYCODE = 13;
  var ESC_KEYCODE = 27;
  var TITLE_MIN_LENGTH = 30;
  var TITLE_MAX_LENGTH = 100;
  var MAX_PRICE = 1000000;
  var PRICE_PLACEHOLDER = 1000;
  var BUNGALO_PRICE = 0;
  var FLAT_PRICE = 1000;
  var HOUSE_PRICE = 5000;
  var PALACE_PRICE = 10000;
  var IMG_WIDTH = 45;
  var IMG_HEIGHT = 40;
  var TIMEOUT_VALUE = 10000;
  var SUCCESSFUL_REQUEST = 200;
  var MAINPIN_X_MIN = 0;
  var MAINPIN_X_MAX = document.querySelector('.map__overlay').offsetWidth;
  var MAINPIN_Y_MIN = 130;
  var MAINPIN_Y_MAX = 630;
  var DEBOUNCE_INTERVAL = 500;

  window.const = {
    AVATAR_WIDTH: AVATAR_WIDTH,
    AVATAR_HEIGHT: AVATAR_HEIGHT,
    MAINPIN_WIDTH: MAINPIN_WIDTH,
    MAINPIN_HEIGHT: MAINPIN_HEIGHT,
    ENTER_KEYCODE: ENTER_KEYCODE,
    ESC_KEYCODE: ESC_KEYCODE,
    TITLE_MIN_LENGTH: TITLE_MIN_LENGTH,
    TITLE_MAX_LENGTH: TITLE_MAX_LENGTH,
    MAX_PRICE: MAX_PRICE,
    PRICE_PLACEHOLDER: PRICE_PLACEHOLDER,
    BUNGALO_PRICE: BUNGALO_PRICE,
    FLAT_PRICE: FLAT_PRICE,
    HOUSE_PRICE: HOUSE_PRICE,
    PALACE_PRICE: PALACE_PRICE,
    IMG_WIDTH: IMG_WIDTH,
    IMG_HEIGHT: IMG_HEIGHT,
    TIMEOUT_VALUE: TIMEOUT_VALUE,
    SUCCESSFUL_REQUEST: SUCCESSFUL_REQUEST,
    MAINPIN_END_HEIGHT: MAINPIN_END_HEIGHT,
    MAINPIN_X_MIN: MAINPIN_X_MIN,
    MAINPIN_X_MAX: MAINPIN_X_MAX,
    MAINPIN_Y_MIN: MAINPIN_Y_MIN,
    MAINPIN_Y_MAX: MAINPIN_Y_MAX,
    DEBOUNCE_INTERVAL: DEBOUNCE_INTERVAL
  };
})();
